### ISSUE TITLE
map shows sanitary station for mostly untagged caravan sites

### ISSUE THREAD

**Issue by lyxys** [giggls/opencampsitemap#24]
One example is osm way 647023234 where the map shows an available sanitary station though none is tagged at the site.

**Comment by giggls** [comment]
This is a intended feature, not a bug.

There are two things happening here:

1. The WMS layer just shows what is mapped regardless where it is located.

What you see in your example  is: https://www.openstreetmap.org/node/6077433020
The repository for the Mapserver style is at https://github.com/giggls/campsite-features

2. Because the object tagged amenity = sanitary_dump_station is located inside the caravan_site polygon the sanitary_dump_station is shown as a feature of the particular site.

**Comment by giggls** [comment]
BTW, this is what I call the POI in POI feature. See my talk at FOSSGIS 2020
https://media.ccc.de/v/fossgis2020-2888-osmpoidb-eine-kontinuierlich-aktualisierte-poi-datenbank-auf-openstreetmap-basis
