### ISSUE TITLE
Migrate to TypeScript?

### ISSUE THREAD

**Issue by wtimme** [giggls/opencampsitemap#53]
> **As** a developer,
> **I want** to use TypeScript instead of vanilla JavaScript,
> **so that** I can harness the power of the compiler

## Acceptance criterias

- A first part of the code base is migrated to TypeScript
- Documentation is added/updated on how to debug/compile/deploy the mixed code base
- The README for developers mentions that we stronly prefer TypeScript over JavaScript, as we consider the latter legacy code

---

## Personal motivation

Every time I am on camping vacation, I come back to this project, as I believe in an Libre approach to camp site discovery (as opposed to, say, "Park4Night"). However, the fact that the code base is still using vanilla JavaScript always startles me a bit. In my professional life, I have learned to appreciate the help that I get when a compiler is looking over my shoulder, and I think that this project here can benefit from that, too.

@giggls, is this something you are willing to consider? Do you have experience with TypeScript? I am willing to do some research and see how we could slowly start this migration. Happy to hear your input on this.

**Comment by giggls** [comment]
Frankly (I hope I have always communicated this enough in the past) I am not that big of a frontend developer. I originally even thought to make the frontend of this Map to be a umap thingy which did unfortunately not work out.

Thus this whole project is currently basically a Javascript based Generator of some 1990ies HTML code because this is all I know about this stuff.

So regarding Typescript, npm etc. I would be happy to pass maintenance of *the whole frontend project* to someone who actually knows how to do this stuff, but I am afraid I am unable to help coding afterwards that much.

This said, I will still be able to support this regarding the backend as well as sysadmin related tasks. Which is basically the area I know better what I am actually doing anyway.

My focus on this project was always twofold. I wanted to make a map which is usable enough for mappers to help improving campsite tagging and I wanted to use it myself mainly a a bikepacker and of course other bikepackers. The third option which is "make this a useful map for the general public" has always been a nice to have thing for me.

So my main focus for the future of this project will definitely be to get a usable offline version for tools like OSMAnd or OrganicMaps rather than working on the Web UI.

**Comment by wtimme** [comment]
Thanks for your thorough response! I agree that since you are "not that big of a frontend developer", it does not make sense to migrate the code and cut you off.

I'm happy to come back to this site again and again when on the road, but for routing and actual investigation of the POIs, I personally tend to use OSMAnd, which is what I believe most other people are doing.

I'm going ahead and close this issue, as I do not intend to work on this anytime soon. If someone disagrees, feel free to comment.

Again, thanks for your response and openness!
