### ISSUE TITLE
Viewing tag power_supply:maxcurrent

### ISSUE THREAD

**Issue by orson-69** [giggls/opencampsitemap#54]
I propose to display the tag power_supply:maxcurrent

With this tag it is especially useful for travelers who use air conditioning, and sometimes it becomes a selection criterion.

Since it can also have more than one value I would use a text line like this:
Power maxcurrent: X Ampere

The tag is still not used much, but in the last year there is starting to be enough data.
https://taginfo.openstreetmap.org/keys/power_supply:maxcurrent#overview

I apologize, I don't speak English, I used Google Translate

**Comment by giggls** [comment]
Hm definitely not relevant for me personally as the maximum current I need is the one my smartphone loader draws :)

Do you have an Idea how this should look like? IMO this is not a feature of a campsite but rather one of individual objects tagged amenity=power_supply. Thus I can not display it as it would be a feature of the whole site.

I consider it even likely, that on a single camp-site there will be multiple objects tagged amenity=power_supply with different maximum-current values. Thus which one would I display then on the site object?

A thing which could instead be easily done is showing these values in addition to the power-supply symbol I currently have.

E.g. in this Example (if they would be tagged):
https://opencampingmap.org/de/#19/48.64590/8.03417/1/1/bef

Is this a good idea? What do you think?

Do you have an example of a site with meaningful tagging regarding this issue?

**Comment by orson-69** [comment]
The characteristic can be either of the single Campsite or of the supply point.

For the average mapping level of the campsites that I have seen, I do not think it is conceivable to identify in detail.

So my idea is to put it as descriptive data, also because, as you can see in the following link, in some campsites the possibility of supplies of different levels is indicated.

https://taginfo.openstreetmap.org/keys/power_supply:maxcurrent#values

In this way, those who want to go to that site have an idea of ​​what they can find.

A flexible solution for all the different mapping levels could be the one you indicated, for campsites with detailed mapping, while I would suggest when I find an image for the others.

In this case I chose a campsite that has a mixed solution, with two different types of currents depending on the pitch.

It would be even more useful to be able to indicate the type of socket, but it seems to me that there is a bit of confusion on how to tag it in Openstreetmap.


![image](https://github.com/user-attachments/assets/8ba2ca84-b1c4-4d5f-9a74-fe2dd552fe03)

**Comment by giggls** [comment]
I consider the image you have been posting mostly a bad idea. As this will promote the tagging of maxcurrent on the tourism=camp_site object rather than on the premises which is not a good idea at all because it is far from clear what this is even supposed to mean.

We currently have 12145 sites featuring a positive power-supply tag (not no) and only 593 of these sites have a power_supply:maxcurrent tag. This is about 20 times as much.

I think this is not a tagging which should be further encouraged to be tagged on a campsite level but rather on the amenities themselves. This holds true even more for plug types. These should be definitely tagged on the amenities themselves and not at the tourism=camp_site level.

I am also not a big fan off using plug-types on the power_supply tag of campsites either and will definitely not encourage people tagging this. Currently I treat plug-types in the power-supply tag of a site simply as yes.

I would rather see people adding something like this on the premises:
amenity=power_supply
socket:...=value
power_supply:...=value

Worst case of such a global tagging would be to acquire a campsite as a node with ridiculous levels of details about the site. I definitely prefer people tagging sites as polygon instead adding amenities as separate nodes or even ways inside the surrounding tourism=camp_site.

A site I consider nicely mapped is for example this one:
https://opencampingmap.org/de/way/211554090#19/48.64602/8.03419/1/1/bef
