### ISSUE TITLE
Error in review stars

### ISSUE THREAD

**Issue by orson-69** [giggls/opencampsitemap#56]
Curious error, I don't know if it was caused by Opencampingmap or Mangrove.
I reviewed an area with two stars and Opencampingmap puts one

https://opencampingmap.org/en/way/1312170397#13/43.8562/10.2695/4/1/7ef
https://mangrove.reviews/list?signature=N05Dw3uBKLMFyKEEOPxWR_AofWvUX9FXpT-gBA-PCIc8RWTAxEVKwsuw69gAgzbDsQvq1XhNRSOhbLNv4Fl5Vw

![image](https://github.com/user-attachments/assets/7186ce41-bd87-410a-8549-77e04a97b8cc)
![image](https://github.com/user-attachments/assets/aa86729a-9a46-4efb-b49a-d3592c24c9c1)

**Comment by giggls** [comment]
To me this looks like a Bug in Mangrove. @wtimme what do you think?

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the starsForRating function to accurately represent the rating with full, half, and empty stars. This should fix the issue where a 2-star rating was being displayed as 1 star.

You can review changes in this commit: https://github.com/lattaai12/giggls-opencampsitemap-56/commit/1fb708a6dbac61a94e01333137dd4e22fd3b17b8.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by giggls** [comment]
Looks reasonable to me. As reviews.js has been contributed by @wtimme I would like to know what he thinks before merging.

**Comment by wtimme** [comment]
The commit that was - apparently - posted by an AI is not correct, as it removes the closing bracket of the function. Please see my pull request for an actual fix.

In addition, I suggest to silence "Latta AI" by blocking their account.
